name: Build Executable

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: windows
            arch: x64
            ext: exe
          - os: macos-latest
            platform: macos
            arch: x64
            ext: app
          - os: macos-14
            platform: macos
            arch: arm64
            ext: app
          - os: ubuntu-latest
            platform: linux
            arch: x64
            ext:

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          architecture: ${{ matrix.arch }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Application
        run: |
          pyinstaller --onefile --add-data 'templates:templates' --add-data 'model:model' --add-data 'user_network:user_network' main.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pyocr-${{ matrix.platform }}-${{ matrix.arch }}
          path: |
            dist/*
